# Data exploring

In [1]:
import pandas as pd

In [35]:
# TODO: Understand connection between all 3 files

## Check bookings csv

- Every product_id always has the same feature_1 value
- Cancellation_date depends on status == 'Cancelled' -> Drop cancellation date because it is always nan when status not cancelled
- Many duplicates -> Drop
- Revenues can be negative due to discounts or other stuff

In [3]:
bookings = pd.read_csv('../data/20260108_bookings.csv')

In [48]:
bookings.dtypes

id                         int64
bkg_id                     int64
cust_id                    int64
product_id                   str
date                       int64
booking_creation_date      int64
status                       str
cancellation_date        float64
gross_revenue            float64
net_revenue              float64
discount_amount          float64
base_currency                str
bkg_nights                 int64
feature_1                    str
feature_2                    str
dtype: object

In [4]:
print(bookings.shape)
bookings.head()

(939559, 15)

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
0,909230845231,915561966350,22344695850,VIQD1,20240223,20230315,Firm,NaN,449.0,399.0,50.0,STG,3,1 Bedroom,CP04
1,499330627169,755257046964,267648736774,XRJA3,20260213,20250920,Firm,NaN,1049.0,969.0,80.0,STG,3,3 Bedroom,WB04
2,307128985849,612723475438,932456893233,RFQD42,20241220,20240620,Firm,NaN,2899.0,2899.0,NaN,STG,3,4 Bedroom,WB04
3,798019035701,373670041030,585026071001,JEHF2U,20240426,20230324,Firm,NaN,529.0,479.0,50.0,STG,3,2 Bedroom,WB04
4,354487128272,528412311583,342967983781,IXQD2,20230721,20221216,Firm,NaN,2648.0,2648.0,NaN,STG,7,2 Bedroom,WB04

### Check feature_1 to product_id correlation

- Yes, correlated

In [54]:
print(f'Feature 1:\n{bookings["feature_1"].unique()}\n')
print(
    f'Feature 2:\n{bookings["feature_2"].unique()}'
)  # Can be ingnored in data ingestion

Feature 1:
<StringArray>
['1 Bedroom', '3 Bedroom', '4 Bedroom', '2 Bedroom', '6 Bedroom', nan]
Length: 6, dtype: str

Feature 2:
<StringArray>
['CP04', 'WB04', 'BB04', 'PB04']
Length: 4, dtype: str

In [60]:
bookings[bookings['feature_1'].isna()]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
178215,156350095197,623766326708,70486109873,XRJA3U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
178760,156350095197,623766326708,70486109873,XRJA3U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
311116,156350095197,623766326708,70486109873,XRQD3K,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
366515,156350095197,623766326708,70486109873,XRJA2U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
608982,156350095197,623766326708,70486109873,XRQD3K,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
716080,156350095197,623766326708,70486109873,XRJA2U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
764934,156350095197,623766326708,70486109873,XRQD3K,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04

In [58]:
bookings[bookings['product_id'] == 'XRJA2U']

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
366515,156350095197,623766326708,70486109873,XRJA2U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04
716080,156350095197,623766326708,70486109873,XRJA2U,20241206,20241205,Expired,NaN,0.0,0.0,NaN,STG,3,NaN,CP04

In [59]:
# Feature 1
count_feature_1_values = bookings.groupby('product_id')['feature_1'].nunique()
count_feature_1_values = count_feature_1_values[count_feature_1_values > 1]
count_feature_1_values

Series([], Name: feature_1, dtype: int64)

### Check id column

- Does not make sense to me

In [49]:
# TODO: Further investigate

In [5]:
bookings[(bookings['product_id'] == 'XRJA3') & (bookings['date'] == 20260213)]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
1,499330627169,755257046964,267648736774,XRJA3,20260213,20250920,Firm,NaN,1049.0,969.0,80.0,STG,3,3 Bedroom,WB04
3058,812615814663,387793604684,11045055272,XRJA3,20260213,20250718,Firm,NaN,929.0,879.0,50.0,STG,3,3 Bedroom,WB04
17685,786229483567,472739390421,66652998905,XRJA3,20260213,20250625,Firm,NaN,879.0,839.0,40.0,STG,3,3 Bedroom,WB04
31580,561353898378,686609568601,1049988350109,XRJA3,20260213,20250824,Firm,NaN,979.0,979.0,NaN,STG,3,3 Bedroom,WB04
31638,342722604688,135865391443,814939294137,XRJA3,20260213,20250304,Firm,NaN,879.0,829.0,50.0,STG,3,3 Bedroom,WB04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913811,188981507741,942677671777,960758782978,XRJA3,20260213,20251205,Firm,NaN,1099.0,1099.0,NaN,STG,3,3 Bedroom,CP04
915477,251326229041,399724941261,66688344759,XRJA3,20260213,20250405,Firm,NaN,879.0,879.0,NaN,STG,3,3 Bedroom,WB04
918172,1070976276871,5163347729,144453894235,XRJA3,20260213,20250502,Firm,NaN,879.0,829.0,50.0,STG,3,3 Bedroom,WB04
931224,163329664132,410373391477,620714439038,XRJA3,20260213,20250802,Firm,NaN,949.0,949.0,NaN,STG,3,3 Bedroom,WB04
937734,188981507741,942677671777,960758782978,XRJA3,20260213,20251205,Firm,NaN,1099.0,1019.0,80.0,STG,3,3 Bedroom,CP04

In [6]:
bookings['id'].value_counts()[lambda x: x > 1]
# id columns is not unique?!?!?

id
679335503950     140
221048871271     136
860566631334     133
136641833786     131
4033526016       125
                ...
1001898206015      2
733716890926       2
675582673431       2
159458185903       2
701306646543       2
Name: count, Length: 43241, dtype: int64

In [ ]:
bookings[bookings['id'] == 733716890926]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
928314,733716890926,377571631766,1041920702598,HVHF2,20260320,20251212,Firm,NaN,1079.0,1079.0,NaN,EUR,3,2 Bedroom,CP04
928962,733716890926,377571631766,1041920702598,HVHF3,20260320,20251212,Firm,NaN,1249.0,1249.0,NaN,EUR,3,3 Bedroom,CP04

In [8]:
bookings[bookings['id'] == 679335503950]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
27115,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
35107,679335503950,236122850019,914276327796,VIND1K,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,1 Bedroom,BB04
46273,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
56733,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
58278,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920806,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
927639,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
934682,679335503950,236122850019,914276327796,VISE4B,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,4 Bedroom,BB04
934865,679335503950,236122850019,914276327796,VIND1K,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,1 Bedroom,BB04
936232,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04

### Check for duplicated rows

- Yes

In [9]:
# Check for duplicates
print(len(bookings))
print(len(bookings[bookings.duplicated(keep=False)]))
print(len(bookings[bookings.duplicated(keep='first')]))

len(bookings.drop_duplicates(keep='first'))

939559
81996
57651

881908

### Check date range

In [50]:
print(bookings['date'].min())
print(bookings['date'].max(), '\n')
# -> Bookings from 2023/04/21 to 2027/04/19

print(bookings['booking_creation_date'].min())
print(bookings['booking_creation_date'].max())
# -> Bookings created from 2018/10/02 to 2025/12/22

20230421
20270419

20181002
20251222

### Check cancelled bookings

- cancellation_date is a float
- correlation

In [12]:
# Cancelled Bookings should be ignored when ingesting data
print(bookings['status'].unique())

print(len(bookings[bookings['status'] == 'Cancelled']) / len(bookings['status']) * 100)
print(len(bookings[bookings['status'] == 'Cancelled']))

<StringArray>
['Firm', 'Cancelled', 'Expired', 'Pending']
Length: 4, dtype: str
6.440894079030694
60516

In [51]:
# Get every valid cancellation date and check if the status is Cancelled
df_cancelled_date = bookings[bookings['cancellation_date'].notna()]
print(len(df_cancelled_date))
print(len(df_cancelled_date[df_cancelled_date['status'] == 'Cancelled']))

60515
60515

### Check revenue and currency

In [15]:
print(
    f'Currencies: {bookings["base_currency"].unique()} \n'
)  # Pfund Sterling (Brit. Pounds) and Euros

print(bookings['gross_revenue'].min())  # Negative values possible
print(bookings['gross_revenue'].max())
print(bookings['gross_revenue'].mean(), '\n')

print(bookings['net_revenue'].min())  # Negative values possible
print(bookings['net_revenue'].max())
print(bookings['net_revenue'].mean())

# bookings[bookings['net_revenue'] == -709.4] # High discount
bookings[bookings['gross_revenue'] == -84.0]  # Looks like a gift :)

Currencies: <StringArray>
['STG', 'EUR']
Length: 2, dtype: str

-84.0
21096.0
986.0465605246717

-709.4
20996.0
965.1628110741316

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
660478,440760336724,762245127320,940079542671,JEQD4K,20240311,20230907,Firm,NaN,-84.0,-84.0,NaN,STG,4,4 Bedroom,WB04

## Check capacity csv

- ID represents the product_id and date (bookable unit)
- One line per bookable unit
- 780 different product_ids
- 1702 different dates
- column names (is_...) suggest boolean but are not
- Looks like overbookings are possible

Sum of is_bookable and is_option equals the available units for new customers

In [16]:
capacity = pd.read_csv('../data/20260108_capacity.csv')

In [61]:
capacity.dtypes

id                 str
product_id         str
calendar_date    int64
is_bookable      int64
is_option        int64
dtype: object

In [17]:
print(capacity.shape)
capacity.head()
# One line per "bookable unit"

(1327560, 5)

           id product_id  calendar_date  is_bookable  is_option
0  42677b926a      XRKO4       20251113            0          0
1  7fe820989a      RFJQ1       20250215            0          0
2  d02ea1b28d     HVQD1A       20231005            0          0
3  ab49f7975b      HVQD3       20270308            0          0
4  01929d8f1d     JEQD3I       20250904            0          0

In [63]:
# TODO: Check different product_ids for pattern :)
capacity[(capacity['product_id'] == 'XRJA3')].sort_values(by='calendar_date')

                 id product_id  calendar_date  is_bookable  is_option
1060841  9710f03248      XRJA3       20230421            3          0
1018228  cf0c5a6ac8      XRJA3       20230422            3          0
470934   96794c7108      XRJA3       20230423            3          0
303144   61ea27c24a      XRJA3       20230424            7          0
443693   0fa69f18e5      XRJA3       20230425            7          0
...             ...        ...            ...          ...        ...
176581   04c66e4605      XRJA3       20271213          172          0
1141486  0e8c04a086      XRJA3       20271214          172          0
858662   d6a6cd195c      XRJA3       20271215          172          0
270129   a68dac3a10      XRJA3       20271216          172          0
179880   098ce23cb1      XRJA3       20271217          172          0

[1702 rows x 5 columns]

In [65]:
print(len(capacity['product_id'].unique()))
# 780 different apartment types
print(len(capacity['calendar_date'].unique()))
# 1702 different dates

print(len(capacity['product_id'].unique()) * len(capacity['calendar_date'].unique()))
# 780 * 1702 = 1327560
# Every product_id has every calendar date listed -> one line per bookable unit

780
1702
1327560

In [ ]:
# TODO: Check the date distribution
print(len(capacity['calendar_date'].unique()))
print(capacity['calendar_date'].min())
print(capacity['calendar_date'].max())

In [22]:
print(f'Is bookable unique values: {capacity["is_bookable"].unique()}\n')
# Count of how many bookable units (product_id + date) are available

print(f'Is option unique values: {capacity["is_option"].unique()}')
# Count of how many bookable units are reservated as optional

# Negativ values = Overbookings?!
# Sum of is_bookable and is_option equals the available units for new customers

Is bookable unique values: [  0   1   3  66 121   5   8  37  75  27   2 140  13  19   9   6  17  73
  88   7   4  39  10  77  50  72  12  63  80 118  42  79  81 106  15 152
  14  58  71  20  35  31  76  25  26 161  28  24  55  33  18  61  29  74
 145  23 242  21  64  86  78 102  34  69 113  11  45  67 103  22 136  30
 111 146  65  40  59  53  16  96 110 141 169 158 117 112 143 104  56  54
 107  32 122  43  97 131  51  60 132 170  70  38 126 172  62 192  46 153
  85 159 101 148 130 134 119  41 108  92 109  47 123  68 120 171 100  90
 160 115  36  57 241  52  98 183 167  48 175 151  91 139  99 127 128  -1
 150 144  44 137  -4 239 129 174 225 138 125 124 166  93 105  83 135  84
 212  49 155 156  94 114 207  87  89 -10 184 149 147 163 173 238 190 164
 142 116 194  -2 133 185 168 195 165 240 231  82 196 232 -16 209 237 157
  -3 191 186 203 211 193 236 205 162 -11 197 199  95 202  -5 213 208 206
 221 182 154 222 224  -7 200 217 201 215]

Is option unique values: [ 0  1  2  3  8  5  7 10 20 91  4 25  6 29 13 36 11 54 51  9 69 42 12 31
 96 83 44 19 97 40 74 30]

## Check prices csv

- ID represents the product_id and date (bookable unit) -> 110.336 unique units
- 264 unique product_ids -> Less then in capacity
- 489 unique dates -> Less then in capacity
    - Not every bookable unit has a price?!
    - Some bookable units have multiple prices?!
    - Maybe because of different length_of_stay but this does not look correct
- length_of_stay is string because of "XN" (Extra Nights?!)
    - Compared to bookings, los has just a small amount available of real bookings

> Every bookable unit has a capacity but not every bookable_unit has a price

> Test hypothese: Every product_id as 552 rows with the same date+length_of_stay pattern

In [23]:
prices = pd.read_csv('../data/20260108_prices.csv')

In [66]:
prices.dtypes

id                    str
product_id            str
date                int64
current_price     float64
length_of_stay        str
dtype: object

In [24]:
print(prices.shape)
prices.head()

(124528, 5)

           id product_id      date  current_price length_of_stay
0  19c3f145a7      IXHF4  20241115         2025.0              3
1  1d1e72c8b2     IXQD32  20260130          822.0              3
2  65851f3235     VISE4D  20251227         3694.0              3
3  12560cf11d     IXQD32  20250718         1385.0              3
4  de95aae83c     JEQD1D  20250721          546.0              4

In [25]:
print(len(prices['id'].unique()))
print(f'Len unique product ids: {len(prices["product_id"].unique())}')
print(f'Len unique dates: {len(prices["date"].unique())}')

110336
Len unique product ids: 264
Len unique dates: 489

In [26]:
prices[prices['id'] == '65851f3235'].head()
# ID represents the product_id and date (bookable unit)

               id product_id      date  current_price length_of_stay
2      65851f3235     VISE4D  20251227         3694.0              3
19274  65851f3235     VISE4D  20251227         1415.0             XN
60077  65851f3235     VISE4D  20251227         4610.0              7
72838  65851f3235     VISE4D  20251227         2381.0              4

In [27]:
df = prices[(prices['product_id'] == 'IXQD32')].sort_values(by='date')
df
# date + length_of_stay = date of next row
# TODO: Evaluate pattern of product_ids - I see one

                id product_id      date  current_price length_of_stay
94560   cc07104e5a     IXQD32  20230421         1454.0              3
20157   04e89a2d51     IXQD32  20230424         1043.0              4
93655   6113a49f7a     IXQD32  20230428         1684.0              3
55705   4a7d05e021     IXQD32  20230501         1145.0              4
30165   d6189be046     IXQD32  20230505         1450.0              3
...            ...        ...       ...            ...            ...
96950   70918ba3e9     IXQD32  20271213         1021.0              4
112815  7b0f3f1f43     IXQD32  20271217          904.0              4
36121   7b0f3f1f43     IXQD32  20271217         2057.0              3
9092    7b0f3f1f43     IXQD32  20271217          294.0             XN
7179    7b0f3f1f43     IXQD32  20271217         2511.0              7

[552 rows x 5 columns]

In [28]:
# Dates
print(f'First date available: {prices["date"].min()}')
print(f'Last data available: {prices["date"].max()}\n')

# Prices
print(f'Min price available: {prices["current_price"].min()}')
print(f'Max price available: {prices["current_price"].max()}\n')

# length_of_stay
print(prices['length_of_stay'].unique())  # XN equals to Extra Night?

First date available: 20230421
Last data available: 20271217

Min price available: 58.0
Max price available: 19446.0

<StringArray>
['3', '4', '7', 'XN', '2']
Length: 5, dtype: str