# Data exploring

In [1]:
import pandas as pd

## Check bookings csv

In [2]:
bookings = pd.read_csv('../data/20260108_bookings.csv')

In [3]:
print(bookings.shape)
bookings.head()

(939559, 15)

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
0,909230845231,915561966350,22344695850,VIQD1,20240223,20230315,Firm,NaN,449.0,399.0,50.0,STG,3,1 Bedroom,CP04
1,499330627169,755257046964,267648736774,XRJA3,20260213,20250920,Firm,NaN,1049.0,969.0,80.0,STG,3,3 Bedroom,WB04
2,307128985849,612723475438,932456893233,RFQD42,20241220,20240620,Firm,NaN,2899.0,2899.0,NaN,STG,3,4 Bedroom,WB04
3,798019035701,373670041030,585026071001,JEHF2U,20240426,20230324,Firm,NaN,529.0,479.0,50.0,STG,3,2 Bedroom,WB04
4,354487128272,528412311583,342967983781,IXQD2,20230721,20221216,Firm,NaN,2648.0,2648.0,NaN,STG,7,2 Bedroom,WB04

## Check capacity csv

In [4]:
capacity = pd.read_csv('../data/20260108_capacity.csv')

In [5]:
print(capacity.shape)
capacity.head()

(1327560, 5)

           id product_id  calendar_date  is_bookable  is_option
0  42677b926a      XRKO4       20251113            0          0
1  7fe820989a      RFJQ1       20250215            0          0
2  d02ea1b28d     HVQD1A       20231005            0          0
3  ab49f7975b      HVQD3       20270308            0          0
4  01929d8f1d     JEQD3I       20250904            0          0

## Check prices csv

In [6]:
prices = pd.read_csv('../data/20260108_prices.csv')

In [7]:
print(prices.shape)
prices.head()

(124528, 5)

           id product_id      date  current_price length_of_stay
0  19c3f145a7      IXHF4  20241115         2025.0              3
1  1d1e72c8b2     IXQD32  20260130          822.0              3
2  65851f3235     VISE4D  20251227         3694.0              3
3  12560cf11d     IXQD32  20250718         1385.0              3
4  de95aae83c     JEQD1D  20250721          546.0              4