# Data exploring

In [69]:
import pandas as pd
import seaborn as sns

## Check bookings csv

In [124]:
bookings = pd.read_csv('../data/20260108_bookings.csv')

In [125]:
print(bookings.shape)
bookings.head()

(939559, 15)

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
0,909230845231,915561966350,22344695850,VIQD1,20240223,20230315,Firm,NaN,449.0,399.0,50.0,STG,3,1 Bedroom,CP04
1,499330627169,755257046964,267648736774,XRJA3,20260213,20250920,Firm,NaN,1049.0,969.0,80.0,STG,3,3 Bedroom,WB04
2,307128985849,612723475438,932456893233,RFQD42,20241220,20240620,Firm,NaN,2899.0,2899.0,NaN,STG,3,4 Bedroom,WB04
3,798019035701,373670041030,585026071001,JEHF2U,20240426,20230324,Firm,NaN,529.0,479.0,50.0,STG,3,2 Bedroom,WB04
4,354487128272,528412311583,342967983781,IXQD2,20230721,20221216,Firm,NaN,2648.0,2648.0,NaN,STG,7,2 Bedroom,WB04

In [ ]:
bookings['id'].value_counts()[lambda x: x > 1]
# id columns is not unique?!?!?

id
679335503950     140
221048871271     136
860566631334     133
136641833786     131
4033526016       125
                ...
1001898206015      2
733716890926       2
675582673431       2
159458185903       2
701306646543       2
Name: count, Length: 43241, dtype: int64

In [149]:
bookings[bookings['id'] == 733716890926]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
928314,733716890926,377571631766,1041920702598,HVHF2,20260320,20251212,Firm,NaN,1079.0,1079.0,NaN,EUR,3,2 Bedroom,CP04
928962,733716890926,377571631766,1041920702598,HVHF3,20260320,20251212,Firm,NaN,1249.0,1249.0,NaN,EUR,3,3 Bedroom,CP04

In [150]:
bookings[bookings['id'] == 679335503950]

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
27115,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
35107,679335503950,236122850019,914276327796,VIND1K,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,1 Bedroom,BB04
46273,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
56733,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
58278,679335503950,236122850019,914276327796,VISE3,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,3 Bedroom,BB04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920806,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
927639,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04
934682,679335503950,236122850019,914276327796,VISE4B,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,4 Bedroom,BB04
934865,679335503950,236122850019,914276327796,VIND1K,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,1 Bedroom,BB04
936232,679335503950,236122850019,914276327796,VISE2,20250227,20240821,Expired,NaN,0.0,0.0,NaN,STG,1,2 Bedroom,BB04

- Id column does not make sense to me!

In [143]:
# Check for duplicates
print(len(bookings))
print(len(bookings[bookings.duplicated(keep=False) == True]))
print(len(bookings[bookings.duplicated(keep='first') == True]))

len(bookings.drop_duplicates(keep='first'))

939559
81996
57651

881908

In [123]:
# Check ids
print(len(bookings['id'].unique()))
print(len(bookings['bkg_id'].unique()))
print(len(bookings['cust_id'].unique()))

857719
857719
857709

In [ ]:
# Investigate dates

print(bookings['date'].dtype)
# Formatted as int -> Format to datetime


print(bookings['date'].min())
print(bookings['date'].max(), '\n')
# -> Bookings from 2023/04/21 to 2027/04/19

print(bookings['booking_creation_date'].min())
print(bookings['booking_creation_date'].max())
# -> Bookings created from 2018/10/02 to 2025/12/22

int64
20230421
20270419

20181002
20251222

In [ ]:
# Cancelled Bookings should be ignored when ingesting data
print(bookings['status'].unique())

print(len(bookings[bookings['status'] == 'Cancelled']) / len(bookings['status']) * 100)
print(len(bookings[bookings['status'] == 'Cancelled']))

<StringArray>
['Firm', 'Cancelled', 'Expired', 'Pending']
Length: 4, dtype: str
6.440894079030694
60516

In [79]:
# Customer id should be ignored when ingesting data
print(f"Unique customers: {len(bookings['cust_id'].unique())}")

# Connection to booking ids?!
print(f"Unique bookings: {len(bookings['bkg_id'].unique())}")

Unique customers: 857709
Unique bookings: 857719

In [ ]:
# Check features
print(f"Feature 1: \n{bookings['feature_1'].unique()} \n")
print(f"Feature 2: \n{bookings['feature_2'].unique()}") # Can be ingnored in data ingestion

Feature 1:
<StringArray>
['1 Bedroom', '3 Bedroom', '4 Bedroom', '2 Bedroom', '6 Bedroom', nan]
Length: 6, dtype: str

Feature 2:
<StringArray>
['CP04', 'WB04', 'BB04', 'PB04']
Length: 4, dtype: str

In [ ]:
print(f'Currencies: {bookings["base_currency"].unique()} \n') # Pfund Sterling (Brit. Pounds) and Euros

print(bookings['gross_revenue'].min()) # Negative values possible
print(bookings['gross_revenue'].max())
print(bookings['gross_revenue'].mean(), '\n')

print(bookings['net_revenue'].min()) # Negative values possible
print(bookings['net_revenue'].max())
print(bookings['net_revenue'].mean())

# bookings[bookings['net_revenue'] == -709.4] # High discount
bookings[bookings['gross_revenue'] == -84.0] # Looks like a gift :)

Currencies: <StringArray>
['STG', 'EUR']
Length: 2, dtype: str

-84.0
21096.0
986.0465605246717

-709.4
20996.0
965.1628110741316

,id,bkg_id,cust_id,product_id,date,booking_creation_date,status,cancellation_date,gross_revenue,net_revenue,discount_amount,base_currency,bkg_nights,feature_1,feature_2
660478,440760336724,762245127320,940079542671,JEQD4K,20240311,20230907,Firm,NaN,-84.0,-84.0,NaN,STG,4,4 Bedroom,WB04

## Check capacity csv

In [151]:
capacity = pd.read_csv('../data/20260108_capacity.csv')

In [173]:
print(capacity.shape)
capacity.head()
# One line per "bookable unit"

(1327560, 5)

           id product_id  calendar_date  is_bookable  is_option
0  42677b926a      XRKO4       20251113            0          0
1  7fe820989a      RFJQ1       20250215            0          0
2  d02ea1b28d     HVQD1A       20231005            0          0
3  ab49f7975b      HVQD3       20270308            0          0
4  01929d8f1d     JEQD3I       20250904            0          0

In [175]:
capacity[capacity['is_option'] != 0]

                 id product_id  calendar_date  is_bookable  is_option
2377     83d3be27ea      VIHF2       20260123           31          1
5944     0fd4ff89dd     RFQD3O       20260226            4          2
7486     11bb5289f4      RFQD3       20250423            2          3
17580    4b00698ae7      RFQD2       20260217           24          8
17847    c028830450     RFQD42       20260324            0          1
...             ...        ...            ...          ...        ...
1314733  5e9d906c19      RFYS3       20260215            0          3
1314752  8f654abf2d     RFQD3O       20260225            4          2
1315255  7181f3e69c      IXJA2       20260622          102          2
1317879  306d459094     RFQD42       20260305            0          3
1322866  7966e68f51      RFYS3       20260401            8          1

[342 rows x 5 columns]

In [ ]:
len(capacity['id'].unique())
# Here, the id looks okay

1327560

In [ ]:
print(len(capacity['product_id'].unique()))
# 780 different apartment types
# TODO: Rename column

print(len(capacity['calendar_date'].unique()))
print(capacity['calendar_date'].min())
print(capacity['calendar_date'].max())

print(len(capacity['product_id'].unique()) * len(capacity['calendar_date'].unique()))
# 780 * 1702 = 1327560
# Every product_id has every calendar date listed -> one line per bookable unit

780
1702
20230421
20271217
1327560

In [ ]:
# TODO: Interpret values
print(f"Is bookable unique values: {capacity['is_bookable'].unique()}\n")
print(f"Is option unique values: {capacity['is_option'].unique()}")

print(capacity['is_option'].value_counts())

# Negativ values = Overbookings?

Is bookable unique values: [  0   1   3  66 121   5   8  37  75  27   2 140  13  19   9   6  17  73
  88   7   4  39  10  77  50  72  12  63  80 118  42  79  81 106  15 152
  14  58  71  20  35  31  76  25  26 161  28  24  55  33  18  61  29  74
 145  23 242  21  64  86  78 102  34  69 113  11  45  67 103  22 136  30
 111 146  65  40  59  53  16  96 110 141 169 158 117 112 143 104  56  54
 107  32 122  43  97 131  51  60 132 170  70  38 126 172  62 192  46 153
  85 159 101 148 130 134 119  41 108  92 109  47 123  68 120 171 100  90
 160 115  36  57 241  52  98 183 167  48 175 151  91 139  99 127 128  -1
 150 144  44 137  -4 239 129 174 225 138 125 124 166  93 105  83 135  84
 212  49 155 156  94 114 207  87  89 -10 184 149 147 163 173 238 190 164
 142 116 194  -2 133 185 168 195 165 240 231  82 196 232 -16 209 237 157
  -3 191 186 203 211 193 236 205 162 -11 197 199  95 202  -5 213 208 206
 221 182 154 222 224  -7 200 217 201 215]

Is option unique values: [ 0  1  2  3  8  5  7 10 20 91  4 25  6 29 13 36 11 54 51  9 69 42 12 31
 96 83 44 19 97 40 74 30]
is_option
0     1327218
1         115
2          72
3          24
6          24
4          20
10         19
5           9
7           9
20          7
25          5
8           4
13          4
11          4
9           3
12          3
29          2
36          2
54          2
19          2
91          1
51          1
69          1
42          1
31          1
96          1
83          1
44          1
97          1
40          1
74          1
30          1
Name: count, dtype: int64

## Check prices csv

In [6]:
prices = pd.read_csv('../data/20260108_prices.csv')

In [7]:
print(prices.shape)
prices.head()

(124528, 5)

           id product_id      date  current_price length_of_stay
0  19c3f145a7      IXHF4  20241115         2025.0              3
1  1d1e72c8b2     IXQD32  20260130          822.0              3
2  65851f3235     VISE4D  20251227         3694.0              3
3  12560cf11d     IXQD32  20250718         1385.0              3
4  de95aae83c     JEQD1D  20250721          546.0              4

In [167]:
print(len(prices['id'].unique()))

110336

In [168]:
prices['id'].value_counts()[lambda x: x > 1]

id
fcf544e2c9    5
73357e36a9    5
65851f3235    4
2f2b5a9748    4
c4fdc83f79    4
             ..
5e5a877299    4
96f9398f55    4
427a12308d    4
08bf654c0a    4
35d4f93c78    4
Name: count, Length: 4730, dtype: int64

In [170]:
prices[prices['id'] == 'fcf544e2c9']

               id product_id      date  current_price length_of_stay
725    fcf544e2c9      XRJA6  20251227         2936.0             XN
26919  fcf544e2c9      XRJA6  20251227         4409.0              7
47079  fcf544e2c9      XRJA6  20251227         8015.0              4
75049  fcf544e2c9      XRJA6  20251227         1809.0             XN
76297  fcf544e2c9      XRJA6  20251227         3975.0              3

In [171]:
prices[prices['product_id'] == 'XRJA6']

                id product_id      date  current_price length_of_stay
128     5c0086372a      XRJA6  20250407         6030.0              4
155     c364e1cb23      XRJA6  20260601         3375.0              4
725     fcf544e2c9      XRJA6  20251227         2936.0             XN
765     72ff7de197      XRJA6  20270322         1844.0              4
1090    71065a4290      XRJA6  20241223         8823.0              7
...            ...        ...       ...            ...            ...
123049  c513ea32cd      XRJA6  20260116         3730.0              3
123197  43d4bc784d      XRJA6  20240304         1843.0              4
123807  30079028ba      XRJA6  20250721         4084.0              4
123980  b773f45f36      XRJA6  20261019         5688.0              4
124183  982d22b999      XRJA6  20270405         4182.0              4

[448 rows x 5 columns]

In [ ]:
print(f"Len unique price ids: {len(prices['id'].unique())}")
print(f"Len unique product ids: {len(prices['product_id'].unique())}")

# ================

print(f"Len unique dates: {len(prices['date'].unique())}")
print(f"First date available: {prices['date'].min()}")
print(f"Last data available: {prices['date'].max()}")
# Check missing dates

# Boxplot for prices
# Check price dependancy to date and product id

# ==================
# Print Boxplot
print(f"Len unique lenght_of_stay {len(prices['length_of_stay'].unique())}")
print(f"Min length_of_stay {prices['length_of_stay'].min()}")
print(f"Max length_of_stay {prices['length_of_stay'].max()}")
print(prices['length_of_stay'].unique())
# Check XN value

Len unique price ids: 110336
Len unique product ids: 264
Len unique dates: 489
First date available: 20230421
Last data available: 20271217
Len unique lenght_of_stay 5
Min length_of_stay 2
Max length_of_stay XN
<StringArray>
['3', '4', '7', 'XN', '2']
Length: 5, dtype: str